# Generated by Django 2.1.1 on 2020-02-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='贴吧名')),
                ('fid', models.CharField(max_length=20, verbose_name='贴吧id')),
                ('is_sign', models.BooleanField(default=False, verbose_name='是否签到')),
                ('retry_time', models.SmallIntegerField(default=0, verbose_name='重试次数')),
                ('status', models.CharField(default='', max_length=100, verbose_name='签到状态')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
                'db_table': 'sign',
            },
        ),
        migrations.CreateModel(
            name='SignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='贴吧名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ret_log', models.TextField(verbose_name='签到日志')),
            ],
            options={
                'verbose_name': '签到日志',
                'verbose_name_plural': '签到日志',
                'db_table': 'sign_log',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='SignTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': '签到总数',
                'verbose_name_plural': '签到总数',
                'db_table': 'sign_total',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bduss', models.CharField(max_length=192, verbose_name='BDUSS')),
                ('username', models.CharField(editable=False, max_length=30, unique=True, verbose_name='贴吧用户名')),
                ('token', models.CharField(editable=False, max_length=100, unique=True, verbose_name='个人TOKEN')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flag', models.IntegerField(default=0, null=True, verbose_name='新用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['-update_time'],
                'get_latest_by': 'created_time',
            },
        ),
        migrations.AddField(
            model_name='signlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.User', verbose_name='所属用户'),
        ),
        migrations.AlterUniqueTogether(
            name='sign',
            unique_together={('name', 'fid', 'user')},
        ),
    ]
