# Generated by Django 2.0.7 on 2019-11-30 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SignIn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='ststus',
            new_name='status',
        ),
    ]
