# Generated by Django 2.1.1 on 2020-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notice',
            field=models.BooleanField(default=False, verbose_name='是否通知'),
        ),
    ]
