# Generated by Django 2.0.7 on 2018-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiebaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bduss', models.CharField(max_length=192, verbose_name='BDUSS')),
                ('username', models.CharField(max_length=30, verbose_name='贴吧用户名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='个人TOKEN')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('idDel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='TiebaYunHui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='贴吧名')),
                ('fid', models.CharField(max_length=20, verbose_name='贴吧id')),
                ('tid', models.CharField(max_length=20, verbose_name='帖子id')),
                ('isLou', models.BooleanField(verbose_name='是否楼中楼')),
                ('floor', models.CharField(max_length=20, null=True, verbose_name='楼层id')),
                ('qid', models.CharField(max_length=20, null=True, verbose_name='楼层号编号')),
                ('tbjingyan', models.IntegerField(null=True, verbose_name='贴吧经验')),
                ('tbdengji', models.IntegerField(null=True, verbose_name='贴吧等级')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('user', models.ManyToManyField(to='YunHui.TiebaUser', verbose_name='所属用户')),
            ],
        ),
    ]
