# Generated by Django 2.0.7 on 2018-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieba',
            name='stop',
            field=models.BooleanField(default=False, verbose_name='是否暂停'),
        ),
        migrations.AlterField(
            model_name='tieba',
            name='isLou',
            field=models.BooleanField(default=False, verbose_name='是否楼中楼'),
        ),
    ]
