# Generated by Django 2.0.7 on 2018-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieba',
            name='time',
            field=models.IntegerField(default=5, verbose_name='回复间隔'),
        ),
    ]
