# Generated by Django 2.0.7 on 2018-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_type',
        ),
        migrations.AddField(
            model_name='user',
            name='i_type',
            field=models.BooleanField(default=True, verbose_name='云回模式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activite',
            field=models.BooleanField(default=True, verbose_name='是否活动'),
        ),
    ]
