# Generated by Django 2.0.7 on 2018-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_new',
        ),
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.IntegerField(default=0, null=True, verbose_name='新用户'),
        ),
    ]
