# Generated by Django 2.0.7 on 2018-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0002_auto_20180816_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(editable=False, max_length=200, unique=True, verbose_name='个人TOKEN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=30, verbose_name='贴吧用户名'),
        ),
    ]
