# Generated by Django 2.0.7 on 2018-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0002_auto_20180814_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='user',
            field=models.ManyToManyField(to='YunHui.User', verbose_name='所属用户'),
        ),
    ]
