# Generated by Django 2.0.7 on 2018-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YunHui', '0004_auto_20180814_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='update_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ptoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stoken',
        ),
        migrations.AddField(
            model_name='sign',
            name='cur_score',
            field=models.IntegerField(default=0, null=True, verbose_name='当前经验'),
        ),
        migrations.AddField(
            model_name='sign',
            name='level_id',
            field=models.IntegerField(default=0, null=True, verbose_name='当前等级'),
        ),
    ]
